name: HungerGames
main: HungerGames\HungerGames
version: 2.13.4
api: [2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5]
authors: ["Kaitododo", "thelucyclub"]

commands:
    hg:
        usage: /hg
        description: HungerGames-Commands
    setrank:
        usage: /setrank
        description: Rank-Commands